/*
 * Abyss Echo - localization module
 * Simple {zh, en} string pairs. UI strings live here; game content data
 * carries its own {zh,en} name/desc pairs in data.js.
 */
var ABYSS = window.ABYSS = window.ABYSS || {};

ABYSS.LANG = {
  builtin: {
    "game_title": { zh: "深渊回响", en: "Abyss Echo" },
    "game_subtitle": { zh: "文字地牢冒险", en: "Text Dungeon RPG" },
    "new_game": { zh: "新的旅程", en: "New Journey" },
    "continue": { zh: "继续探索", en: "Continue" },
    "reset": { zh: "重置存档", en: "Reset Save" },
    "reset_confirm": { zh: "确定要抹去深渊中的一切痕迹吗？此操作不可恢复。", en: "Erase every trace in the abyss? This cannot be undone." },
    "save_export": { zh: "导出存档", en: "Export Save" },
    "save_import": { zh: "导入存档", en: "Import Save" },
    "save_imported": { zh: "存档已导入", en: "Save imported" },
    "save_invalid": { zh: "存档无效", en: "Invalid save" },
    "saved": { zh: "已自动保存", en: "Game saved" },
    "hp": { zh: "生命", en: "HP" },
    "mp": { zh: "魔力", en: "MP" },
    "atk": { zh: "攻击", en: "ATK" },
    "def": { zh: "防御", en: "DEF" },
    "spd": { zh: "速度", en: "SPD" },
    "luck": { zh: "幸运", en: "LCK" },
    "gold": { zh: "金币", en: "Gold" },
    "depth": { zh: "层数", en: "Depth" },
    "level": { zh: "等级", en: "Level" },
    "xp": { zh: "经验", en: "XP" },
    "fight": { zh: "战斗", en: "Fight" },
    "attack": { zh: "攻击", en: "Attack" },
    "guard": { zh: "防御", en: "Guard" },
    "skill": { zh: "技能", en: "Skill" },
    "flee": { zh: "逃跑", en: "Flee" },
    "item": { zh: "道具", en: "Item" },
    "inventory": { zh: "背包", en: "Inventory" },
    "equipment": { zh: "装备", en: "Equipment" },
    "stats": { zh: "属性", en: "Stats" },
    "log": { zh: "日志", en: "Log" },
    "achievements": { zh: "成就", en: "Achievements" },
    "settings": { zh: "设置", en: "Settings" },
    "sound_on": { zh: "音效：开", en: "Sound: On" },
    "sound_off": { zh: "音效：关", en: "Sound: Off" },
    "music_on": { zh: "音乐：开", en: "Music: On" },
    "music_off": { zh: "音乐：关", en: "Music: Off" },
    "fast_text": { zh: "快节奏文本", en: "Fast Text" },
    "normal_text": { zh: "打字机效果", en: "Typewriter Effect" },
    "language": { zh: "语言", en: "Language" },
    "help": { zh: "帮助", en: "Help" },
    "back": { zh: "返回", en: "Back" },
    "victory": { zh: "胜利", en: "Victory" },
    "defeat": { zh: "败亡", en: "Defeat" },
    "game_over": { zh: "你死了……", en: "You have died..." },
    "restart": { zh: "再次深入", en: "Descend Again" },
    "use": { zh: "使用", en: "Use" },
    "equip": { zh: "装备", en: "Equip" },
    "unequip": { zh: "卸下", en: "Unequip" },
    "sell": { zh: "出售", en: "Sell" },
    "buy": { zh: "购买", en: "Buy" },
    "take": { zh: "拾取", en: "Take" },
    "leave": { zh: "离开", en: "Leave" },
    "descend": { zh: "深入下一层", en: "Descend Deeper" },
    "rest": { zh: "扎营休息", en: "Make Camp" },
    "search": { zh: "搜索房间", en: "Search Room" },
    "continue_btn": { zh: "继续", en: "Continue" },
    "no_item": { zh: "空空如也", en: "Nothing here" },
    "no_gold": { zh: "金币不足", en: "Not enough gold" },
    "no_mp": { zh: "魔力不足", en: "Not enough MP" },
    "full_inventory": { zh: "背包已满", en: "Inventory full" },
    "explored": { zh: "已探索", en: "Explored" },
    "kills": { zh: "击杀", en: "Kills" },
    "deaths": { zh: "死亡次数", en: "Deaths" },
    "best_depth": { zh: "最深记录", en: "Best Depth" },
    "play_time": { zh: "游戏时间", en: "Play Time" },
    "floor": { zh: "第 {n} 层", en: "Floor {n}" },
    "floor_name_depth": { zh: "深渊第 {n} 层", en: "Abyss Floor {n}" },
    "enemy": { zh: "敌人", en: "Enemy" },
    "elite_bonus": { zh: "双倍奖励", en: "2x Rewards" },
    "dmg": { zh: "造成 {n} 点伤害", en: "dealt {n} damage" },
    "take_dmg": { zh: "受到 {n} 点伤害", en: "took {n} damage" },
    "crit": { zh: "暴击！", en: "Critical!" },
    "dodged": { zh: "闪避了攻击", en: "dodged the attack" },
    "blocked": { zh: "格挡了攻击", en: "blocked the attack" },
    "victory_msg": { zh: "战斗胜利！获得 {xp} 经验，{gold} 金币", en: "Victory! +{xp} XP, +{gold} gold" },
    "level_up": { zh: "等级提升！现在是 {n} 级", en: "Level up! Now level {n}" },
    "died": { zh: "你被 {n} 杀死了", en: "You were slain by {n}" },
    "fled": { zh: "你成功逃跑了", en: "You fled successfully" },
    "trap_hit": { zh: "触发了陷阱！", en: "A trap triggered!" },
    "chest": { zh: "你打开了宝箱", en: "You opened the chest" },
    "found_item": { zh: "发现了 {n}", en: "Found {n}" },
    "achievement_unlocked": { zh: "成就解锁：{n}", en: "Achievement unlocked: {n}" },
    "ending": { zh: "结局", en: "Ending" },
    "new_record": { zh: "新纪录！", en: "New record!" },
    "status_applied": { zh: "{n} 附着了 {s}", en: "{n} was afflicted with {s}" },
    "status_end": { zh: "{s} 效果消失了", en: "{s} wore off" },
    "healed": { zh: "恢复了 {n} 点生命", en: "restored {n} HP" },
    "mp_restore": { zh: "恢复了 {n} 点魔力", en: "restored {n} MP" },
    "skills_tab": { zh: "技能", en: "Skills" },
    "tutorial": { zh: "教程", en: "Tutorial" },
    "codex": { zh: "深渊图鉴", en: "Abyss Codex" },
    "monsters": { zh: "怪物", en: "Monsters" },
    "items": { zh: "物品", en: "Items" },
    "codex_unknown": { zh: "尚未遭遇。深入深渊以解锁此条目。", en: "Not yet encountered. Descend deeper to unlock." },
    "daily_best": { zh: "今日最佳：第 {n} 层 · 击杀 {k}", en: "Today's best: Floor {n} · {k} kills" },
    "daily_enter": { zh: "进入每日挑战？今日规则：", en: "Enter the daily challenge? Today's rules:" },
    "daily_rules": { zh: "每日挑战每天变化规则组合，死亡即结束。成绩仅记录今日最佳。", en: "Rules change daily; death ends the run. Only today's best counts." },
    "quest_start": { zh: "接受了委托", en: "Quest accepted" },
    "quest_abandon": { zh: "放弃了委托", en: "Quest abandoned" },
    "quest_done": { zh: "委托完成", en: "Quest complete" },
    "quest_current": { zh: "当前委托", en: "Current quest" },
    "reward": { zh: "奖励", en: "Reward" },
    "room_searched_more": { zh: "这间房间已搜刮殆尽，深渊中还有更多秘密。", en: "This room is picked clean; the abyss holds more secrets." },
    "room_searched_done": { zh: "这间房间已搜刮殆尽，深渊在更深处等待。", en: "This room is picked clean; the depths await." },
    "mist_floor": { zh: "迷雾笼罩着这一层深渊。", en: "Mist shrouds this floor of the abyss." },
    "chest_opened": { zh: "你打开了宝箱……", en: "You opened the chest..." },
    "trap_triggered": { zh: "触发了陷阱！", en: "A trap triggered!" },
    "trap_dodged": { zh: "你险险避开了机关！", en: "You narrowly dodged the mechanism!" },
    "camp_spot": { zh: "一块相对安全的高地，适合扎营休息。", en: "A relatively safe ledge, fit for making camp." },
    "ev_fountain_drink": { zh: "饮下泉水（恢复 40% 生命）", en: "Drink the spring (restore 40% HP)" },
    "ev_fountain_grab": { zh: "取走泉底的硬币（+30 金币，30% 诅咒）", en: "Take the coins (+30 gold, 30% curse)" },
    "ev_fountain_curse": { zh: "泉水反噬，你被虚弱诅咒缠身！", en: "The spring turns on you; a weakening curse clings to you!" },
    "ev_altar_gift": { zh: "献上 50 金币，祈求祝福", en: "Offer 50 gold for a blessing" },
    "ev_altar_bless": { zh: "祭坛吞噬金币，一道祝福没入你的身体。", en: "The altar devours the gold; a blessing sinks into your body." },
    "ev_altar_defile": { zh: "亵渎祭坛（-15 生命，获得 60 金币）", en: "Defile the altar (-15 HP, gain 60 gold)" },
    "ev_altar_frag": { zh: "触碰祭坛上的碎片（真相碎片·其一）", en: "Touch the fragment on the altar (Fragment of Truth I)" },
    "ev_tomb_dig": { zh: "挖掘坟墓", en: "Dig the grave" },
    "ev_tomb_hand": { zh: "墓穴中伸出一只枯手！", en: "A withered hand bursts from the grave!" },
    "ev_shrine_pray": { zh: "虔诚祈祷（祝福 5 回合）", en: "Pray devoutly (blessing for 5 turns)" },
    "ev_shrine_power": { zh: "神像低语，力量注入你的四肢。", en: "The idol whispers; power floods your limbs." },
    "ev_shrine_smash": { zh: "砸碎神像（获得 25 金币）", en: "Smash the idol (gain 25 gold)" },
    "ev_shrine_coins": { zh: "神像裂开，滚落几枚古币。", en: "The idol cracks; ancient coins spill out." },
    "ev_vein_mine": { zh: "开采矿脉（获得金币，10% 塌方）", en: "Mine the vein (gain gold, 10% collapse)" },
    "ev_statue_frag": { zh: "取走雕像掌心的碎片（真相碎片·其二）", en: "Take the fragment from the statue's palm (Fragment of Truth II)" },
    "ev_statue_gaze": { zh: "凝视雕像的双眼（祝福，5% 陷入疯狂）", en: "Gaze into the statue's eyes (blessing, 5% madness)" },
    "ev_statue_mad": { zh: "你的心智被深渊撕开了一道口子……", en: "The abyss tears a rift in your mind..." },
    "ev_statue_truth": { zh: "深渊的真相在你眼中一闪而过。", en: "The truth of the abyss flashes through your eyes." },
    "ev_nest_attack": { zh: "突袭蛛巢", en: "Raid the nest" },
    "ev_nest_spider": { zh: "巢穴里扑出一只巨大的腐蚀蜘蛛！", en: "A colossal corrosive spider bursts from the nest!" },
    "ev_supply_open": { zh: "打开补给箱", en: "Open the supply cache" },
    "ev_fortune_pay": { zh: "支付 50 金币，求一道吉运（祝福 3 回合）", en: "Pay 50 gold for fortune (blessing, 3 turns)" },
    "ev_fortune_glow": { zh: "塔罗牌泛起金光，命运向你微笑。", en: "The tarot glows gold; fate smiles upon you." },
    "ev_fortune_free": { zh: "免费听一段预言（40% 得金币 / 30% 得祝福 / 30% 遭诅咒）", en: "Hear a prophecy free (40% gold / 30% blessing / 30% curse)" },
    "ev_fortune_gold": { zh: "「你口袋里的硬币会变多。」——预言应验了。", en: "'Your pockets will grow heavy.' — the prophecy holds." },
    "ev_fortune_ally": { zh: "「你命中有贵人相助。」——一阵暖意笼罩了你。", en: "'A patron walks beside you.' — warmth washes over you." },
    "ev_fortune_omen": { zh: "「你……你身上缠绕着不祥。」老者脸色大变。", en: "'Y-you... misfortune coils around you.' The elder pales." },
    "ev_library_60": { zh: "支付 80 金币，研读《经验典籍》（+40 XP）", en: "Pay 80 gold to study the Arcane Tome (+40 XP)" },
    "ev_library_read": { zh: "书页上的文字化为流光涌入你的脑海。", en: "The words turn to light and pour into your mind." },
    "ev_library_recipe": { zh: "支付 60 金币，抄录两张魔力药水配方", en: "Pay 60 gold to copy two mana potion recipes" },
    "ev_library_trace": { zh: "你小心翼翼地拓印了两页配方。", en: "You carefully trace two pages of recipes." },
    "ev_library_free": { zh: "免费翻阅残卷（30% 发现一件小物品）", en: "Browse the ruined tomes free (30% odds of a small find)" },
    "ev_library_rot": { zh: "残卷已经腐烂得无法辨认。", en: "The tomes have rotted beyond recognition." },
    "quest_board_offer": { zh: "接受委托", en: "Accept quest" },
    "ev_forge_repair": { zh: "修复伤口（50 金币，完全恢复生命）", en: "Repair wounds (50 gold, full HP)" },
    "ev_forge_healed": { zh: "铁匠一锤砸下，你的伤口竟愈合了。", en: "The smith's hammer falls; your wounds knit shut." },
    "ev_forge_buy": { zh: "你买下了 {n}", en: "You bought {n}" },
    "ev_forge_gear": { zh: "铸造装备：{n} — {g} 金币（9 折）", en: "Forge gear: {n} — {g} gold (10% off)" },
    "ev_forge_made": { zh: "铁匠为你量身打造了 {n}", en: "The smith forged {n} just for you" },
    "death_by": { zh: "你被 {n} 杀死了", en: "You were slain by {n}" },
    "died_abyss": { zh: "你死在了第 {n} 层", en: "You died on floor {n}" },
    "status_afflicted": { zh: "{n} 使你{ s}", en: "{n} afflicts you with {s}" },
    "skill_cd": { zh: "技能冷却中", en: "Skill on cooldown" },
    "flee_fail": { zh: "逃跑失败！", en: "Failed to flee!" },
    "flee_locked": { zh: "Boss 战无法逃跑！", en: "Bosses cannot be fled from!" },
    "hp_restored": { zh: "恢复了 {n} 点生命", en: "restored {n} HP" },
    "chest_gold": { zh: "宝箱中装着 {n} 金币！", en: "The chest holds {n} gold!" },
    "enemy_dmg_suffix": { zh: "（敌人）", en: " (to enemy)" },
    "took_effect": { zh: "生效", en: "took effect" },
    "camp_rest": { zh: "⛺ 你扎营休息，恢复了体力与魔力", en: "⛺ You make camp and recover strength and mana" },
    "prestige_gained": { zh: "🌀 深渊刻印 +{n}！你的力量在深渊中回响……", en: "🌀 Abyss Mark +{n}! Your power echoes through the abyss..." },
    "echo_shattered": { zh: "🌪 回响 Boss 被击碎！{n} 的残响消散了……", en: "🌪 The echo boss shatters! The remnants of {n} fade..." },
    "deeper_dark": { zh: "你坠入了更深的黑暗……", en: "You fall into a deeper darkness..." },
    "rift_opened": { zh: "💀 深渊在震颤……通往核心的裂隙已经开启。", en: "💀 The abyss trembles... a rift to the core has opened." },
    "awaken_intro": { zh: "你睁开眼，四周是永恒的黑暗。你决定深入深渊。", en: "You wake. Eternal darkness surrounds you. You decide to descend." },
    "endless_locked": { zh: "需要至少 1 枚深渊刻印才能进入无尽深渊（先完成一个结局并转生）。", en: "Requires at least 1 Abyss Mark (complete an ending and rebirth first)." },
    "endless_start": { zh: "你从第 13 层开始——主线之后的深渊。等级 8，带上旅途的馈赠。", en: "You begin at floor 13 — the abyss beyond the story. Level 8, with gifts from the road." },
    "no_save_new": { zh: "没有找到存档，开始新的旅程。", en: "No save found. A new journey begins." },
    "defeated": { zh: "已击败", en: "Defeated" },
    "undefeated": { zh: "未击败", en: "Undefeated" },
    "help_explore": { zh: "⛏ 探索：进入房间后搜索，可能遭遇战斗、事件或宝藏。", en: "⛏ Explore: search rooms; battles, events, and treasures await." },
    "help_combat": { zh: "⚔ 战斗：攻击 / 防御（格挡减伤）/ 技能（消耗魔力）/ 道具 / 逃跑。", en: "⚔ Combat: attack / guard (block) / skills (MP) / items / flee." },
    "help_cooldown": { zh: "✦ 技能冷却：使用后需等待数回合。防御可叠加格挡。", en: "✦ Cooldowns: skills recharge over turns. Guard for extra block." },
    "help_elite": { zh: "🌟 精英怪：15% 概率出现，属性更高、双倍奖励，必掉额外战利品。", en: "🌟 Elites: 15% chance, higher stats, double rewards, guaranteed bonus loot." },
    "help_boss": { zh: "💀 Boss：第 3/6/9/12 层有 Boss，击败第 12 层 Boss 后开启深渊核心。", en: "💀 Bosses: floors 3/6/9/12; beating floor 12's boss opens the abyss core." },
    "help_fragments": { zh: "💠 真相碎片：祭坛、雕像、深渊之主各藏一枚碎片，集齐可解锁真结局。", en: "💠 Fragments: altar, statue, and the Abyss Lord each hold one; gather all three for the true ending." },
    "help_prestige_ui": { zh: "🌀 转生：达成任一结局后可在结局界面转生，获得永久「深渊刻印」（属性 +4%/级、金币 +5%/级）。", en: "🌀 Rebirth: after any ending, transcend for permanent abyss marks (+4% stats, +5% gold per mark)." },
    "help_inv": { zh: "📦 背包：可装备武器/护甲/饰品，消耗品在战斗中直接使用。", en: "📦 Inventory: equip weapons/armor/trinkets; use consumables in combat." },
    "help_save": { zh: "💾 存档：自动保存 + 手动导出/导入（设置面板）。", en: "💾 Saves: autosave + manual export/import (settings)." },
    "help_keys": { zh: "⌨ 快捷键：战斗中 1=攻击 2=防御 3=逃跑，4-9=技能。", en: "⌨ Hotkeys: 1=attack, 2=guard, 3=flee, 4-9=skills in combat." },
    "daily_challenge": { zh: "☀️ 每日挑战", en: "☀️ Daily Challenge" },
    "endless": { zh: "🌀 无尽深渊", en: "🌀 Endless Abyss" },
    "elite_prefix": { zh: "精英·", en: "Elite " },
    "echo_prefix": { zh: "回响·", en: "Echo " },
    "tutorial_moves": { zh: "使用底部按钮移动，⚔攻击 / 🛡防御 / ✦技能 / 🏃逃跑。每 3 层会出现一个 Boss。", en: "Use the buttons below. ⚔Attack / 🛡Guard / ✦Skills / 🏃Flee. A boss awaits every 3 floors." },
    "boss_enraged": { zh: "进入了狂暴形态", en: "enters its enraged form" },
    "combat_summary": { zh: "战斗总结", en: "Combat Summary" },
    "turns": { zh: "{n} 回合", en: "{n} turns" },
    "dmg_dealt": { zh: "输出 {n}", en: "dealt {n}" },
    "dmg_taken": { zh: "承伤 {n}", en: "taken {n}" },
    "about": { zh: "关于", en: "About" },
    "about_desc": { zh: "零依赖文字地牢冒险。回合制战斗、5 位 Boss、转生、每日挑战、无尽模式、图鉴与委托。数据驱动的平衡设计（3000 局模拟，通关率 23.6%）。", en: "A zero-dependency text dungeon RPG: turn-based combat, 5 bosses, rebirth, daily challenge, endless mode, codex & quests. Balance tuned by 3000-run simulation (23.6% win rate)." },
    "guide": { zh: "玩法指南", en: "Gameplay Guide" },
    "ev_mirage_fight": { zh: "深入幻境追击黑影", en: "Chase the shadow into the mirage" },
    "ev_mirage_phantom": { zh: "雾中的黑影凝成实体，向你扑来！", en: "The shadow in the mist solidifies and lunges!" },
    "ev_mirage_smoke": { zh: "驱散篝火残烟（40% 空 / 30% 金币 / 30% 药水）", en: "Dispel the campfire smoke (40% nothing / 30% gold / 30% potion)" },
    "ev_mirage_ash": { zh: "残烟散去，只有灰烬。", en: "The smoke clears — only ash remains." },
    "ev_field_sword": { zh: "拾起一柄断剑（获得随机武器）", en: "Pick up a broken blade (random weapon)" },
    "ev_field_pouch": { zh: "搜刮尸袋（获得 40-90 金币）", en: "Loot the corpse pouches (40-90 gold)" },
    "ev_field_bury": { zh: "埋葬无名尸骨（获得祝福）", en: "Bury the nameless bones (gain a blessing)" },
    "ev_field_bless": { zh: "你为无名者合上双眼，一道祝福悄然落下。", en: "You close the stranger's eyes; a quiet blessing settles on you." },
    "daily_today": { zh: "☀️ 今日规则", en: "☀️ Today's rules" },
    "daily_today_item": { zh: "{n}：{d}", en: "{n}: {d}" },
    "best_floor": { zh: "最佳 {n} 层", en: "Best floor {n}" },
    "journey_summary": { zh: "旅程总结", en: "Journey Summary" },
    "best": { zh: "最佳", en: "best" },
    "elite_kills": { zh: "精英", en: "elites" },
    "multikill_bosses": { zh: "Boss", en: "bosses" },
    "ach_progress": { zh: "🏆 成就 {n}/{t}", en: "🏆 Achievements {n}/{t}" },
    "charging": { zh: "蓄力重击", en: "winds up a heavy strike" },
    "ev_vault_left": { zh: "打开左边的黑匣", en: "Open the left chest" },
    "ev_vault_middle": { zh: "打开中间的黑匣", en: "Open the middle chest" },
    "ev_vault_right": { zh: "打开右边的黑匣", en: "Open the right chest" },
    "ev_vault_bless": { zh: "匣中涌出一团温暖的光。", en: "Warm light pours from the chest." },
    "ev_vault_curse": { zh: "黑匣张开利齿咬住了你的手！", en: "The chest snaps its fangs around your hand!" },
    "ms_25": { zh: "里程碑：无尽第 {n} 层！", en: "Milestone: endless floor {n}!" },
    "echo_next": { zh: "下一层将遭遇回响 Boss——做好准备！", en: "An echo boss awaits on the next floor — prepare!" },
    "difficulty": { zh: "难度", en: "Difficulty" },
    "difficulty_set": { zh: "难度已设为：{n}（新旅程生效）", en: "Difficulty set to {n} (applies to new journeys)" },
    "daily_streak": { zh: "最佳连续挑战 {n} 天", en: "Best daily streak {n} days" },
    "daily_streak_now": { zh: "当前 {n} 天", en: "currently {n}" },
    "vs_equipped": { zh: "对比已装备", en: "vs equipped" },
    "quest_completed": { zh: "已完成 {n} 个委托", en: "{n} quests completed" }
  }
};

ABYSS.T = function (key, vars) {
  var lang = ABYSS.LANG.current || "zh";
  var table = ABYSS.LANG.builtin[key] || { zh: key, en: key };
  var s = table[lang] || table.zh || key;
  if (vars) {
    for (var k in vars) {
      s = s.split("{" + k + "}").join(vars[k]);
    }
  }
  return s;
};

ABYSS.LANG.name = function (entry) {
  if (!entry) return "?";
  var lang = ABYSS.LANG.current || "zh";
  return entry.name ? (entry.name[lang] || entry.name.zh || entry.name) : (entry[lang] || entry.zh || String(entry));
};

ABYSS.LANG.desc = function (entry) {
  var lang = ABYSS.LANG.current || "zh";
  return entry.desc ? (entry.desc[lang] || entry.desc.zh || entry.desc) : "";
};

/* CommonJS export for node tests */
if (typeof module !== "undefined" && module.exports) {
  module.exports = { ABYSS: ABYSS };
}











